// Json file with Description of the data about Avengers and their powers
export const Avengers = {
    "Avengers": [
        {
            "name": "Thanos",
            "description" : `The Thanos unde omnis iste natus error sit voluiptatem aquae ab illo invetore veritatis et quasi architecto beatae vitae dicta sunt explicabo Aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt, Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius . Modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`,
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",        
            "bgImage": "/assets/images/bgImage1.jpg",
            "descImage": "/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#5C00D7",
            "colorGradient": "",
            "actor":"Josh Brolin",
            "actorApi":"",
        },
        {
            "name": "Capitan America",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#321DFE",
            "colorGradient": "",
            "actor":"Chris Evans",
            "actorApi":"",
        },
        {
            "name": "Iron Man",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#FF1D31",
            "colorGradient": "",
            "actor":"Robert Downey Jr.",
            "actorApi":"",
        },
        {
            "name": "Thor",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#A50136",
            "colorGradient": "",
            "actor":"Chris Hemsworth",
            "actorApi":"",
        },
        {
            "name": "Doctor Strange",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#FF0A39",
            "colorGradient": "",
            "actor":"Benedict Cumberbatch",
            "actorApi":"",
        },
        {
            "name": "Black Widow",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#D9AA14",
            "colorGradient": "",
            "actor":"Scarlett Johansson",
            "actorApi":"",
        },
        {
            "name": "Star Lord",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#EF5D24",
            "colorGradient": "#8424DE",
            "actor":"Chris Pratt",
            "actorApi":"",
        },
        {
            "name": "Hulk",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#08C247",
            "colorGradient": "",
            "actor":"Mark Ruffalo",
            "actorApi":"",
        },
        {
            "name": "Iron Spider",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#E6033B",
            "colorGradient": "",
            "actor":"Tom Holland",
            "actorApi":"",
        },
        {
            "name": "Black Panther",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#5813FF",
            "colorGradient": "#8200FE",
            "actor":"Chadwick Boseman",
            "actorApi":"",
        },
        {
            "name": "Gamora",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#24F540",
            "colorGradient": "",
            "actor":"Zoe Saldana",
            "actorApi":"",
        },
        {
            "name": "Vision",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#FFF227",
            "colorGradient": "",
            "actor":"Paul Bettany",
            "actorApi":"",
        },
        {
            "name": "Shuri",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#152AAA",
            "colorGradient": "#7C00FF",
            "actor":"Letitia Wright",
            "actorApi":"",
        },
        {
            "name": "Groot",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradinet",
            "colorTheme": "#05CB2C",
            "colorGradient": "#FB0026",
            "actor":"Vin Diesel",
            "actorApi":"",
        },
        {
            "name": "Okoye",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradinet",
            "colorTheme": "#54024A",
            "colorGradient": "#FB0026",
            "actor":"Danai Gurira",
            "actorApi":"",
        },
        {
            "name": "Rocket",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#FDFA0B",
            "colorGradient": "#FC872A",
            "actor":"Bradley Cooper",
            "actorApi":"",
        },
        {
            "name": "Falcon",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#FF0140",
            "colorGradient": "#",
            "actor":"Anthony Mackie",
            "actorApi":"",
        },
        {
            "name": "Scarlet Witch",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#FF0F38",
            "colorGradient": "#F26A12",
            "actor":"Elizabeth Olsen",
            "actorApi":"",
        },
        {
            "name": "Drax",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#5717A9",
            "colorGradient": "#3C9C88",
            "actor":"Dave Bautista",
            "actorApi":"",
        },
        {
            "name": "Nebula",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#033BF4",
            "colorGradient": "#0269D2",
            "actor":"Karen Gillan",
            "actorApi":"",
        },
        {
            "name": "War Machine",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "gradient",
            "colorTheme": "#C8C9CB",
            "colorGradient": "#7A898E",
            "actor":"Don Cheadle",
            "actorApi":"",
        },
        {
            "name": "Mantis",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#28BD47",
            "colorGradient": "",
            "actor":"Pom Klementieff",
            "actorApi":"",
        },
        {
            "name": "Winter Soldier",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#DBB12B",
            "colorGradient": "",
            "actor":"Sebastian Stan",
            "actorApi":"",
        },
        {
            "name": "Wong",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "/assets/images/mainBg.jpg",
            "bgImage": "",
            "descImage":"/assets/images/descImage.png",
            "colorThemeType": "single",
            "colorTheme": "#FF142B",
            "colorGradient": "",
            "actor":"Benedict Wong",
            "actorApi":"",
        },
        
    ]
}

