// Json file with Description of the data about Avengers and their powers
export const castAvengers = {
    "Avengers": [
        {
            "name": "Thanos",
            "description" : `The Thanos unde omnis iste natus error sit voluiptatem aquae ab illo invetore veritatis et quasi architecto beatae vitae dicta sunt explicabo Aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt, Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius . Modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`,
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#5C00D7",
            "colorGradient": "",
        },
        {
            "name": "Capitan America",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#321DFE",
            "colorGradient": "",
        },
        {
            "name": "Capitan America",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#FF1D31",
            "colorGradient": "",
        },
        {
            "name": "Thor",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#A50136",
            "colorGradient": "",
        },
        {
            "name": "Doctor Strange",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#FF0A39",
            "colorGradient": "",
        },
        {
            "name": "Black Widow",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#D9AA14",
            "colorGradient": "",
        },
        {
            "name": "Star Lord",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#EF5D24",
            "colorGradient": "#8424DE",
        },
        {
            "name": "Hulk",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#08C247",
            "colorGradient": "",
        },
        {
            "name": "Iron Spider",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#E6033B",
            "colorGradient": "",
        },
        {
            "name": "Black Panther",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#5813FF",
            "colorGradient": "#8200FE",
        },
        {
            "name": "Gamora",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#24F540",
            "colorGradient": "",
        },
        {
            "name": "Vision",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#FFF227",
            "colorGradient": "",
        },
        {
            "name": "Shuri",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#152AAA",
            "colorGradient": "#7C00FF",
        },
        {
            "name": "Groot",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradinet",
            "colorTheme": "#05CB2C",
            "colorGradient": "#FB0026",
        },
        {
            "name": "Okoye",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradinet",
            "colorTheme": "#54024A",
            "colorGradient": "#FB0026",
        },
        {
            "name": "Rocket",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#FDFA0B",
            "colorGradient": "#FC872A",
        },
        {
            "name": "Falcon",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#FF0140",
            "colorGradient": "#",
        },
        {
            "name": "Scarlet Witch",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#FF0F38",
            "colorGradient": "#F26A12",
        },
        {
            "name": "Drax",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#5717A9",
            "colorGradient": "#3C9C88",
        },
        {
            "name": "Nebula",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#033BF4",
            "colorGradient": "#0269D2",
        },
        {
            "name": "War Machine",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "gradient",
            "colorTheme": "#C8C9CB",
            "colorGradient": "#7A898E",
        },
        {
            "name": "Mantis",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#28BD47",
            "colorGradient": "",
        },
        {
            "name": "Winter Soldier",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#DBB12B",
            "colorGradient": "",
        },
        {
            "name": "Wong",
            "description" : "",
            "description_full" : "",
            "description_image" : "",
            "navImage": "https://i.annihil.us/u/prod/marvel/i/mg/6/20/5232158ed8a6b/standard_xlarge.jpg",
            "colorThemeType": "single",
            "colorTheme": "#FF142B",
            "colorGradient": "",
        },
        
    ]
}

